name = "PersistenceDiagramsBase"
uuid = "b1ad91c1-539c-4ace-90bd-ea06abc420fa"
authors = ["mtsch <matijacufar@gmail.com>"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1.1"
